apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-recommender

spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-recommender
  template:
    metadata:
      labels:
        app: job-recommender

    spec:
      containers:
        - name: job-recommender-container
          image: au.icr.io/recommender-namespace/recommender
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
